name = "triagem-photoselect"
compatibility_date = "2023-12-01"

# Configuração para Cloudflare Pages
pages_build_output_dir = "dist"

[build]
command = "npm run build"
cwd = "."

[build.upload]
format = "directory"
dir = "./dist"

# Variáveis de ambiente para produção
[env.production.vars]
ENVIRONMENT = "production"