name = "triagem"
compatibility_date = "2023-12-01"

# Configuração específica para Cloudflare Pages
[build]
command = "npm run build"
cwd = "."

# Configuração de upload para Pages
[env.production]
name = "triagem"